# Generated by Django 3.2.7 on 2021-10-24 09:22

import datetime
from django.db import migrations, models
import kess.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('avatar', models.CharField(default='🙂', max_length=1)),
                ('name', models.CharField(max_length=32, unique=True, validators=[kess.models.is_ascii])),
                ('points', models.IntegerField(blank=True, default=None, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 10, 24, 11, 22, 5, 332131))),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('favs', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=200, unique=True, verbose_name='Kess?')),
                ('reponse', models.CharField(max_length=200, verbose_name='Réponse')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_ready_to_publish', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(verbose_name='date published')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('created_by', models.CharField(default='anonyme', max_length=200)),
                ('category', models.CharField(choices=[('Divers', 'Divers'), ('Jeux vidéo', 'Jeux vidéo'), ('Films et séries', 'Films et séries'), ('Expressions', 'Expressions'), ('Alimentation', 'Alimentation'), ('Sport', 'Sport'), ('Célébrités et personnages', 'Célébrités et personnages'), ('Art et mode', 'Art et mode')], default=kess.models.CategoryChoice['DIVERS'], max_length=200, verbose_name='Catégorie')),
                ('foundList', models.TextField(blank=True, default='')),
                ('nbTries', models.IntegerField(blank=True, default=None, null=True)),
                ('upVotes', models.TextField(blank=True, default='')),
                ('downVotes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('kessId', models.CharField(blank=True, default='', max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
    ]
