# Generated by Django 3.2.7 on 2021-10-04 09:36

from django.db import migrations, models
import kess.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=32)),
                ('points', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=200, unique=True)),
                ('reponse', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_ready_to_publish', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(verbose_name='date published')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('category', models.CharField(choices=[('Divers', 'Divers'), ('Jeux vidéo', 'Jeux vidéo'), ('Films et séries', 'Films et séries'), ('Expressions', 'Expressions'), ('Alimentation', 'Alimentation'), ('Sport', 'Sport'), ('Célébrités et personnages ', 'Célébrités et personnages ')], default=kess.models.CategoryChoice['DIVERS'], max_length=200)),
            ],
        ),
    ]
