# Generated by Django 3.2.7 on 2021-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kess_text', models.CharField(max_length=200)),
                ('kess_staff', models.BooleanField()),
                ('kess_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
