# Generated by Django 3.2.7 on 2021-10-24 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 11, 22, 36, 433786)),
        ),
    ]
