# Generated by Django 3.2.7 on 2021-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0002_rename_question_kess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kess',
            old_name='kess_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='kess',
            old_name='kess_text',
            new_name='emoji',
        ),
        migrations.RenameField(
            model_name='kess',
            old_name='kess_staff',
            new_name='isStaff',
        ),
        migrations.AddField(
            model_name='kess',
            name='reponse',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
