# Generated by Django 3.2.7 on 2021-10-04 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0002_alter_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 14, 42, 38, 55349)),
        ),
    ]
