# Generated by Django 3.2.7 on 2021-09-29 21:34

from django.db import migrations, models
import kess.models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0003_auto_20210915_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='kess',
            name='category',
            field=models.CharField(choices=[(kess.models.CategoryChoice['DIVERS'], 'Divers'), (kess.models.CategoryChoice['GAMES'], 'Jeux vidéo'), (kess.models.CategoryChoice['MOVIE'], 'Films et séries'), (kess.models.CategoryChoice['EXPRESSION'], 'Expressions'), (kess.models.CategoryChoice['CULINARY'], 'Alimentation'), (kess.models.CategoryChoice['SPORT'], 'Sport')], default=kess.models.CategoryChoice['DIVERS'], max_length=5),
        ),
        migrations.AlterField(
            model_name='kess',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
