# Generated by Django 3.2.7 on 2021-10-05 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0003_alter_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kess',
            name='foundList',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 10, 14, 20, 686622)),
        ),
    ]
