# Generated by Django 3.2.7 on 2021-10-03 22:05

from django.db import migrations, models
import kess.models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0004_auto_20210929_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kess',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='kess',
            name='date',
        ),
        migrations.AddField(
            model_name='kess',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='kess',
            name='is_ready_to_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kess',
            name='published_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='kess',
            name='category',
            field=models.CharField(choices=[('Divers', 'Divers'), ('Jeux vidéo', 'Jeux vidéo'), ('Films et séries', 'Films et séries'), ('Expressions', 'Expressions'), ('Alimentation', 'Alimentation'), ('Sport', 'Sport'), ('Célébrités et personnages ', 'Célébrités et personnages ')], default=kess.models.CategoryChoice['DIVERS'], max_length=200),
        ),
        migrations.AlterField(
            model_name='kess',
            name='emoji',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
