# Generated by Django 3.2.7 on 2021-10-05 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0005_auto_20211005_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 14, 26, 20, 533630)),
        ),
    ]
