# Generated by Django 3.2.7 on 2021-10-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0005_auto_20211004_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kess',
            name='created_at',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='kess',
            name='published_at',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
