# Generated by Django 3.2.7 on 2021-10-05 13:16

import datetime
from django.db import migrations, models
import kess.models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0006_alter_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kess',
            name='created_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='kess',
            name='category',
            field=models.CharField(choices=[('Divers', 'Divers'), ('Jeux vidéo', 'Jeux vidéo'), ('Films et séries', 'Films et séries'), ('Expressions', 'Expressions'), ('Alimentation', 'Alimentation'), ('Sport', 'Sport'), ('Célébrités et personnages ', 'Célébrités et personnages ')], default=kess.models.CategoryChoice['DIVERS'], max_length=200, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 15, 16, 15, 913231)),
        ),
    ]
