# Generated by Django 3.2.7 on 2021-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0007_auto_20211005_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default='date published'),
        ),
    ]
