# Generated by Django 3.2.7 on 2021-10-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0008_alter_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='🙂', max_length=32),
        ),
        migrations.AlterField(
            model_name='kess',
            name='created_by',
            field=models.CharField(default='anonyme', max_length=200),
        ),
    ]
