# Generated by Django 3.2.7 on 2021-10-08 12:08

import datetime
from django.db import migrations, models
import kess.models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0012_alter_tile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kess',
            name='category',
            field=models.CharField(choices=[('Divers', 'Divers'), ('Jeux vidéo', 'Jeux vidéo'), ('Films et séries', 'Films et séries'), ('Expressions', 'Expressions'), ('Alimentation', 'Alimentation'), ('Sport', 'Sport'), ('Célébrités et personnages', 'Célébrités et personnages'), ('Art et mode', 'Art et mode')], default=kess.models.CategoryChoice['DIVERS'], max_length=200, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 14, 8, 22, 100958)),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[kess.models.is_ascii]),
        ),
    ]
