# Generated by Django 3.2.7 on 2021-10-08 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0013_auto_20211008_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 14, 10, 23, 376802)),
        ),
    ]
