# Generated by Django 3.2.7 on 2021-10-12 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0014_alter_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kess',
            name='nbTries',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 13, 59, 29, 667785)),
        ),
    ]
