# Generated by Django 3.2.7 on 2021-10-13 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0016_auto_20211012_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 14, 10, 15, 269851)),
        ),
    ]
