# Generated by Django 3.2.7 on 2021-10-13 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0018_auto_20211013_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 15, 20, 35, 310499)),
        ),
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.TextField(blank=True, default=None),
        ),
    ]
