# Generated by Django 3.2.7 on 2021-10-14 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0019_auto_20211013_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='kessId',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 14, 55, 19, 418423)),
        ),
    ]
