# Generated by Django 3.2.7 on 2021-10-15 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0020_auto_20211014_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='kess',
            name='downVotes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='kess',
            name='upVotes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 9, 50, 28, 105056)),
        ),
    ]
