# Generated by Django 3.2.7 on 2021-10-15 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0021_auto_20211015_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kess',
            name='downVotes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kess',
            name='upVotes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 12, 33, 30, 876866)),
        ),
    ]
