# Generated by Django 3.2.7 on 2021-10-19 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0022_auto_20211015_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 20, 29, 25, 821077)),
        ),
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
