# Generated by Django 3.2.7 on 2021-10-19 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kess', '0023_auto_20211019_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 20, 31, 50, 904815)),
        ),
    ]
